### ISSUE TITLE
CSV format used

### ISSUE THREAD

**Issue by olivierobert** [Quentin-34/MyGoogleParser#20]
The file upload processing seems to expect the following format:

```
keyword_1;keyword_2;keyword_3
```

This differs from the usually expected format, especially since the UI accepts only a `.csv` file.

https://github.com/Quentin-34/MyGoogleParser/blob/e01bbbe30fab8281429356b886dc282b2517912e/MyGoogleParser.SPA/client-app/src/components/upload.vue?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L24-L29

From its name, the CSV format usually uses commas:

```
keyword_1,keyword_2,keyword_3
``` 

Or Columns:

```
keyword_1
keyword_2
keyword_3
``` 

While there are no technical concerns, if the format expected uses a semi-colon, it would be best to:
1. Document it in the README. Tip for developers.
2. Add a template file in the UI so that end-users can download it and use it for their uploads. Tip for UX.

**Comment by Quentin-34** [comment]
A template is indeed a good way of easing the user experience. I have put a tooltip on the page explaining the number max. of keywords + comma-separated. It is probably not visible enough

**Comment by olivierobert** [comment]
Indeed, there is a mention in the upload page:

https://github.com/Quentin-34/MyGoogleParser/blob/e01bbbe30fab8281429356b886dc282b2517912e/MyGoogleParser.SPA/client-app/src/components/upload.vue?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L19

In terms of visibility, it could indeed be more prominent 👍
